### ISSUE TITLE
'RawMol' object has no attribute 'monomers'

### ISSUE THREAD

**Issue by chem-william** [binghuang2018/aqml#1]
When running the following command:
```bash
python gen_orca_jobs -loose -t optg -m b3lyp -b vdz -n 1 g7/*.sdf
```

I get the following output:
```bash
 ** set --maxit 60
 ** set --mem 1000
 ** set --calcfc 6
 first input file:  g7/frag_01_c00001.sdf
Traceback (most recent call last):
  File "gen_orca_jobs", line 152, in <module>
    mols = rawm.monomers
AttributeError: 'RawMol' object has no attribute 'monomers'
```

It seems the RawMol class is missing the monomers attribute. Is it possible for the repo to be updated with this? Or am I doing something wrong?

**Comment by binghuang2018** [comment]
Try to change the relevant line in file `gen_orca_jobs` to
```bash
     mols = rawm.fragments #monomers
```
instead. Or git clone the latest version.

**Comment by chem-william** [comment]
Perfect! That seemed to fix it. Thank you very much
